### ISSUE TITLE
error

### ISSUE THREAD

**Issue by onismera** [HuCaoFighting/Swin-Unet#121]
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [160,0,0] Assertion `t >= 0 && t < n_classes` failed.                                          
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [161,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [162,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [163,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [164,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [165,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [166,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [167,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [168,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [169,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [170,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [171,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [172,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [173,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [174,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [175,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [176,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [177,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [178,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [179,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [180,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [181,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [182,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [183,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [184,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [185,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [186,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [187,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [188,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [189,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [190,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [191,0,0] Assertion `t >= 0 && t < n_classes` failed.
  0%|                                         | 0/150 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    trainer_synapse(args, net, args.output_dir)
  File "/mnt/C/znmd_ztc/ReID/Swin-Unet-main/trainer.py", line 68, in trainer_synapse
    loss_dice = dice_loss(outputs, label_batch, softmax=True)
  File "/mnt/C/znmd_ztc/anaconda3/envs/Swin-Unet-main/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/C/znmd_ztc/ReID/Swin-Unet-main/utils.py", line 43, in forward
    class_wise_dice.append(1.0 - dice.item())
RuntimeError: CUDA error: device-side assert triggered
Hello, I encountered this problem while reproducing the model. Do you have a solution?

**Comment by yjq-yes** [comment]
Sorry to disrupt. I encountered the same problem and I've set it to 9, but it doesn't change.
``` python train.py --dataset Synapse --cfg configs/swin_tiny_patch4_window7_224_lite.yaml --root_path "data/Synapse/" --max_epochs 150 --output_dir "output"  --img_size 224 --base_lr 0.05 --batch_size 6 --num_classes 9 ```:

:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [353,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [354,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [355,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [356,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [672,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [673,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [448,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [449,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [576,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [577,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [578,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [579,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [580,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [581,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [582,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [583,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [224,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [894,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [895,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [951,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [952,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [953,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [954,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [955,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [190,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [191,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [635,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [636,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [637,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [638,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [639,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [580,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [581,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [857,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [858,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [859,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [860,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [861,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [862,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [863,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [413,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [414,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [415,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [502,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [503,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [504,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [505,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [506,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [507,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [508,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [509,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [510,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [511,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [802,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [803,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [804,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [805,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [806,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
  0%|                                         | 0/150 [00:29<?, ?it/s]
Traceback (most recent call last):
  File "E:\Swin-Unet-main\Swin-Unet-main\train.py", line 101, in <module>
    trainer_synapse(args, net, args.output_dir)
  File "E:\Swin-Unet-main\Swin-Unet-main\trainer.py", line 68, in trainer_synapse
    loss_dice = dice_loss(outputs, label_batch, softmax=True)
  File "E:\anaconda\envs\DL\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\anaconda\envs\DL\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Swin-Unet-main\Swin-Unet-main\utils.py", line 35, in forward
    target = self._one_hot_encoder(target)
  File "E:\Swin-Unet-main\Swin-Unet-main\utils.py", line 17, in _one_hot_encoder
    temp_prob = input_tensor == i  # * torch.ones_like(input_tensor)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by onismera** [comment]
> n_class

是调整n_class的值为9，num_class和n_class是两个不同的参数，都要设置为9才可以

**Comment by onismera** [comment]
> Sorry to disrupt. I encountered the same problem and I've set it to 9, but it doesn't change. `python train.py --dataset Synapse --cfg configs/swin_tiny_patch4_window7_224_lite.yaml --root_path "data/Synapse/" --max_epochs 150 --output_dir "output" --img_size 224 --base_lr 0.05 --batch_size 6 --num_classes 9`:
> 
> :\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [353,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [354,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [355,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [356,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [672,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [673,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [448,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [449,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [576,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [577,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [578,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [579,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [580,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [581,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [582,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [583,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [224,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [894,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [3,0,0], thread: [895,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [951,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [952,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [953,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [954,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [955,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [190,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [191,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [635,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [636,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [637,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [638,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [639,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [580,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [581,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [857,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [858,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [859,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [860,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [861,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [862,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [863,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [413,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [414,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [415,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [502,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [503,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [504,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [505,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [506,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [507,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [508,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [509,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [510,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [2,0,0], thread: [511,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [802,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [803,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [804,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [805,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [806,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed. C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\NLLLoss2d.cu:106: block: [4,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed. 0%| | 0/150 [00:29<?, ?it/s] Traceback (most recent call last): File "E:\Swin-Unet-main\Swin-Unet-main\train.py", line 101, in trainer_synapse(args, net, args.output_dir) File "E:\Swin-Unet-main\Swin-Unet-main\trainer.py", line 68, in trainer_synapse loss_dice = dice_loss(outputs, label_batch, softmax=True) File "E:\anaconda\envs\DL\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "E:\anaconda\envs\DL\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl return forward_call(*args, **kwargs) File "E:\Swin-Unet-main\Swin-Unet-main\utils.py", line 35, in forward target = self._one_hot_encoder(target) File "E:\Swin-Unet-main\Swin-Unet-main\utils.py", line 17, in _one_hot_encoder temp_prob = input_tensor == i # * torch.ones_like(input_tensor) RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

是调整n_class的值为9，num_class和n_class是两个不同的参数，都要设置为9才可以

**Comment by onismera** [comment]
> you need set args.n_class = 9

Thank you for your answer. The problem has been solved so far, but my final test results are 3-4 percentage points lower than those in the paper, and the visualization results are also poor and jagged. Overall, they are not as good as transunet. How should this problem be solved?

**Comment by aixiaobaikkk** [comment]
> > you need set args.n_class = 9
> 
> Thank you for your answer. The problem has been solved so far, but my final test results are 3-4 percentage points lower than those in the paper, and the visualization results are also poor and jagged. Overall, they are not as good as transunet. How should this problem be solved?

that‘s noraml，I can't reproduce it, and of course many other people have reproduced it. Under this framework, the results of unet are better than this, so you know...

**Comment by onismera** [comment]
> > > you need set args.n_class = 9
> > 
> > 
> > Thank you for your answer. The problem has been solved so far, but my final test results are 3-4 percentage points lower than those in the paper, and the visualization results are also poor and jagged. Overall, they are not as good as transunet. How should this problem be solved?
> 
> that‘s noraml，I can't reproduce it, and of course many other people have reproduced it. Under this framework, the results of unet are better than this, so you know...

hahahaha，Understood, it seems like I also need to do some tricks

**Comment by yjq-yes** [comment]
可以！解决了！谢谢哥们

**Comment by onismera** [comment]
> 可以！解决了！谢谢哥们

ok的，你训练测试完之后把你的测试指标发给俺瞅瞅，我复现的比论文低了3-4个点，可视化结果也不太行

**Comment by aixiaobaikkk** [comment]
> > 可以！解决了！谢谢哥们
> 
> ok的，你训练测试完之后把你的测试指标发给俺瞅瞅，我复现的比论文低了3-4个点，可视化结果也不太行

我最多也就跑到77的样子，感觉很难复现出来，作者又不公开权重文件，就很难搞，我在论文里直接引用的他的结果，我复现不出来他的结果以至于我的消融实验没法和swin unet对比，在其他数据集上swin unet结果也不容乐观，最大的创新点可能就是第一个纯Transformer结构的unet把，这个问题也困扰我到现在，或许真的复现不出...

**Comment by aixiaobaikkk** [comment]
> SwinUnet has already been extensively tested and validated by numerous researchers. Its performance has consistently proven to be superior to U-Net and TransUNet on widely recognized benchmarks such as Synapse and ISIC datasets.
> 
> I kindly request that you carefully review the provided codes and avoid making unsubstantiated or negative comments about the method.

Sorry, I am very sure of your contribution. As the first unet model with a pure Transformer structure, it has given me a lot of encouragement. I did not mean to give you a negative review. I will check my code carefully and apologize to you again.

**Comment by mrbird643** [comment]
> > SwinUnet has already been extensively tested and validated by numerous researchers. Its performance has consistently proven to be superior to U-Net and TransUNet on widely recognized benchmarks such as Synapse and ISIC datasets.
> > I kindly request that you carefully review the provided codes and avoid making unsubstantiated or negative comments about the method.
> 
> Sorry, I am very sure of your contribution. As the first unet model with a pure Transformer structure, it has given me a lot of encouragement. I did not mean to give you a negative review. I will check my code carefully and apologize to you again.

May I ask if you have reached the precision of the thesis?

**Comment by onismera** [comment]
> > > 可以！解决了！谢谢哥们
> > 
> > 
> > ok的，你训练测试完之后把你的测试指标发给俺瞅瞅，我复现的比论文低了3-4个点，可视化结果也不太行
> 
> 哥们请问你后面实现了文的精度吗？能告诉我您的相关参数改动以及代码改动吗

没解决，还是比论文里面的低，我也没管了，反正也只是做个对比实验

**Comment by mrbird643** [comment]
> > > > 可以！解决了！谢谢哥们
> > > 
> > > 
> > > ok的，你训练测试完之后把你的测试指标发给俺瞅瞅，我复现的比论文低了3-4个点，可视化结果也不太行
> > 
> > 
> > 哥们请问你后面实现了文的精度吗？能告诉我您的相关参数改动以及代码改动吗
> 
> 没解决，还是比论文里面的低，我也没管了，反正也只是做个对比实验

我想请问一下您，在训练时也有包含着模型的验证，验证数据集是哪一部分，还有val.txt文件code文件中并未包含。文件中只含有train.txt以及test_vol.txt，因为在。我前面训练时把test_vol.txt改成val.txt文件了进行了模型训练，又或者说test_vol.txt就是代码的val.txt。

**Comment by aixiaobaikkk** [comment]
> > > SwinUnet has already been extensively tested and validated by numerous researchers. Its performance has consistently proven to be superior to U-Net and TransUNet on widely recognized benchmarks such as Synapse and ISIC datasets.
> > > I kindly request that you carefully review the provided codes and avoid making unsubstantiated or negative comments about the method.
> > 
> > 
> > Sorry, I am very sure of your contribution. As the first unet model with a pure Transformer structure, it has given me a lot of encouragement. I did not mean to give you a negative review. I will check my code carefully and apologize to you again.
> 
> May I ask if you have reached the precision of the thesis?

没有哈哈哈

**Comment by aixiaobaikkk** [comment]
> > > > > 可以！解决了！谢谢哥们
> > > > 
> > > > 
> > > > ok的，你训练测试完之后把你的测试指标发给俺瞅瞅，我复现的比论文低了3-4个点，可视化结果也不太行
> > > 
> > > 
> > > 哥们请问你后面实现了文的精度吗？能告诉我您的相关参数改动以及代码改动吗
> > 
> > 
> > 没解决，还是比论文里面的低，我也没管了，反正也只是做个对比实验
> 
> 我想请问一下您，在训练时也有包含着模型的验证，验证数据集是哪一部分，还有val.txt文件code文件中并未包含。文件中只含有train.txt以及test_vol.txt，因为在。我前面训练时把test_vol.txt改成val.txt文件了进行了模型训练，又或者说test_vol.txt就是代码的val.txt。

只有训练集和测试集，照理说应该取最后一个epoch结果或者交叉验证，but...

**Comment by mrbird643** [comment]
> > > > > > 可以！解决了！谢谢哥们
> > > > > 
> > > > > 
> > > > > ok的，你训练测试完之后把你的测试指标发给俺瞅瞅，我复现的比论文低了3-4个点，可视化结果也不太行
> > > > 
> > > > 
> > > > 哥们请问你后面实现了文的精度吗？能告诉我您的相关参数改动以及代码改动吗
> > > 
> > > 
> > > 没解决，还是比论文里面的低，我也没管了，反正也只是做个对比实验
> > 
> > 
> > 我想请问一下您，在训练时也有包含着模型的验证，验证数据集是哪一部分，还有val.txt文件code文件中并未包含。文件中只含有train.txt以及test_vol.txt，因为在。我前面训练时把test_vol.txt改成val.txt文件了进行了模型训练，又或者说test_vol.txt就是代码的val.txt。
> 
> 只有训练集和测试集，照理说应该取最后一个epoch结果或者交叉验证，but...

那应该怎么去解决FileNotFoundError: [Errno 2] No such file or directory: './lists/Synapse\\val.txt'
报错问题，更改代码不进行验证？还是说有其它什么办法解决不知道您能不能分享告知在下

**Comment by zlm12345678** [comment]
> > > > > > 可以！解决了！谢谢哥们
> > > > > 
> > > > > 
> > > > > ok的，你训练测试完之后把你的测试指标发给俺瞅瞅，我复现的比论文低了3-4个点，可视化结果也不太行
> > > > 
> > > > 
> > > > 哥们请问你后面实现了文的精度吗？能告诉我您的相关参数改动以及代码改动吗
> > > 
> > > 
> > > 没解决，还是比论文里面的低，我也没管了，反正也只是做个对比实验
> > 
> > 
> > 我想请问一下您，在训练时也有包含着模型的验证，验证数据集是哪一部分，还有val.txt文件代码文件中并未包含。文件中只含有train.txt以及test_vol.txt，因为在。我前面训练时把test_vol.txt改成val.txt文件了进行了模型训练，又或者说test_vol.txt就是代码的val.txt。
> 
> 只有训练集和测试集，照理说应该取最后一个epoch结果或者交叉验证，但......

May I ask whether you have solved the issue of the missing `val` file? If so, could you please share your solution with me?
